import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";

export default function Home() {
  const handleBtnOnClick = () => {
    console.log("Btn on click");
  };

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleBtnOnClick={handleBtnOnClick}
        />
      </main>
    </>
  );
}
